### PR TITLE
fix move of tasks

### PR DESCRIPTION
**Pull request by rlanhe**
Fix the problem of tasks not being moved from the previous journal to the current one (see #7)

### CODE REVIEW

**Comment by luhmann** [comment]
@rlanhe Great thank you for the fix. @QWxleA Would you consider merging and releasing this?

**Comment by matthjes** [comment]
Please merge this fix, currently the plugin is not usable.

**Comment by dmil** [comment]
+1 [this solution](https://github.com/QWxleA/Unfinished-business/issues/7#issuecomment-1398058595) worked for me, but a PR merge would be great. Thanks!

**Comment by rdiezsj** [comment]
Merge this fix, please

**Pull request merged**
